---
- name: Terminate instances
  hosts: tag_class_load_rammler:tag_class_load_rabbitmq:tag_class_load_testclient
  gather_facts: false

  tasks:
    - name: Remove instance
      local_action: ec2 state=absent region=eu-central-1 instance_ids={{ ec2_id }}

- name: Terminate RDS instance
  hosts: localhost

  tasks:
    - rds:
        command: delete
        region: eu-central-1
        instance_name: lshift-de-rammler-load-db
