- name: Provision and register rabbitmq instances
  hosts: localhost
  gather_facts: false
  vars:
    amount: 5
    aws_region: eu-central-1

  tasks:
    - name: Provision a set of rabbitmq instances on ec2
      ec2:
         group: lshift-de-vpc-internal
         instance_type: t2.nano
         image: ami-96d2cefa
         region: '{{ aws_region }}'
         key_name: lshift-de-vpc
         wait: true
         exact_count: '{{ amount }}'
         count_tag:
            class: load-rabbitmq
         instance_tags:
            VPC: lshift-de-vpc
            class: load-rabbitmq
         vpc_subnet_id: subnet-afe2e2c6
      register: ec2

    - name: Add new instances to host group
      add_host: hostname={{ item.private_ip }} groupname=ec2,rabbitmq
      with_items: '{{ec2.tagged_instances}}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2.tagged_instances}}'

    - name: Refresh inventory
      meta: refresh_inventory
