- name: Configure rabbitmq instances
  hosts: tag_class_load_rabbitmq
  gather_facts: false

  roles:
    - role: rabbitmq
      user: '{{ ec2_private_ip_address }}'
      password: rammler
    - role: swap
    - role: riemann-tools

  tasks:
    - name: Set hostname to something meaningful
      hostname: name="load-rabbitmq_{{ inventory_hostname|replace('.','-') }}"
