- name: Provision and register rammler instances
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Provision a rammler instance on ec2
      ec2:
         group: lshift-de-vpc-internal
         instance_type: c4.large
         image: ami-96d2cefa
         region: '{{ aws_region }}'
         key_name: lshift-de-vpc
         wait: true
         instance_tags:
            VPC: lshift-de-vpc
         vpc_subnet_id: subnet-afe2e2c6
      register: ec2

    - name: Add new instances to host group
      add_host: hostname={{ item.private_ip }} groupname=aws,rammler instance={{ item }}
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=20 timeout=300 state=started
      with_items: '{{ec2.instances}}'

    - name: Write inventory file
      template: src=templates/inventory.json.j2 dest=./inventory-rammler.json


- name: Configure rammler instance
  hosts: rammler
  vars:
    endpoint: "{{ (lookup('file', 'rds.json') | from_json).instance.endpoint }}"

  tasks:
    - name: install lshift repo
      yum: name=https://s3-eu-central-1.amazonaws.com/lshift-de-rpms/alldist/noarch/lshift.de-release-0-1.noarch.rpm state=present

    - name: install rammler
      yum: name=rammler state=latest disable_gpg_check=true

    - name: install nss-myhostname
      yum: name=nss-myhostname state=latest

    - name: configure rammler
      template: src=templates/rammler.edn.j2 dest=/etc/rammler.edn

    - name: start rammler
      service: name=rammler state=started
