- name: Get database facts
  hosts: localhost
  gather_facts: false

  tasks:
    - rds:
        command: facts
        instance_name: lshift-de-rammler-load-db
        region: eu-central-1
      register: rds

- name: Configure rammler instance
  hosts: tag_class_load_rammler

  roles:
    - role: rammler
      endpoint: '{{ hostvars.localhost.rds.instance.endpoint }}'
    - role: riemann-tools

  tasks:
    - name: Set hostname to something meaningful
      hostname: name="load-rammler_{{ inventory_hostname|replace('.','-') }}"
