---
- name: Configure client instances
  hosts: tag_class_load_testclient
  vars:
    endpoint: "{{ groups['tag_class_load_rammler'][0] }}"
    index: "{{ play_hosts.index(inventory_hostname) }}"

  roles:
  - role: testclient

  tasks:
    - name: start test script
      command: ruby /client.rb {{ endpoint }} {{ groups['tag_class_load_rabbitmq'][index|int] }} rammler 10000000
