- name: Provision test client instances
  hosts: localhost
  gather_facts: false
  vars:
    amount: 5
    ids: "{{ (lookup('file', 'inventory.json') | from_json).instance_ids }}"

  tasks:
    - name: Provision a set of test client instances on ec2
      ec2:
         group: lshift-de-vpc-internal
         instance_type: t2.nano
         image: ami-96d2cefa
         region: '{{ aws_region }}'
         key_name: lshift-de-vpc
         wait: true
         exact_count: '{{ amount }}'
         count_tag:
            Name: rabbitmq-load-client
         instance_tags:
            VPC: lshift-de-vpc
         vpc_subnet_id: subnet-afe2e2c6
      register: ec2

    - name: Add new instances to host group
      add_host: hostname={{ item.private_ip }} groupname=aws,test-client instance={{ item }} id={{ ids.pop() }}
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=20 timeout=300 state=started
      with_items: '{{ec2.instances}}'

    - name: Write inventory file
      template: src=templates/inventory.json.j2 dest=./inventory-clients.json


- name: Configure client instances
  hosts: test-client
  vars:
    endpoint: "{{ (lookup('file', 'inventory-rammler.json') | from_json).instance.endpoint }}"

  tasks:
    - name: install ruby
      yum: name=ruby state=latest

    - name: install rubygems
      yum: name=rubygems state=latest

    - name: install dependencies
      gem: name=bunny state=present

    - name: copy test script to machines
      copy: src=files/client.rb dest=/

    - name: start test script
      shell: ruby /client.rb {{ endpoint }} {{ id }} rammler 1000000 &
