- name: Provision test client instances
  hosts: localhost
  gather_facts: false
  vars:
    ids: groups['tag_class_load_rabbitmq']
    aws_region: eu-central-1

  tasks:
    - name: Provision a set of test client instances on ec2
      ec2:
         group: lshift-de-vpc-internal
         instance_type: t2.nano
         image: ami-96d2cefa
         region: '{{ aws_region }}'
         key_name: lshift-de-vpc
         wait: true
         exact_count: '{{ ids|length }}'
         count_tag:
            Name: load-testclient
         instance_tags:
            VPC: lshift-de-vpc
            class: load-testclient
         vpc_subnet_id: subnet-afe2e2c6
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host={{ item.private_ip }} port=22 delay=20 timeout=300 state=started
      with_items: '{{ec2.instances}}'
