---
- name: install rabbitmq
  yum: name=rabbitmq-server state=latest

- name: start rabbitmq server
  service: name=rabbitmq-server state=started

- name: add rabbitmq user
  rabbitmq_user: user={{ user }}
                 password={{ password }}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
